matrix:
  include:
  - os: linux
    sudo: false
    language: android
    components:
      - tools
      - build-tools-27.0.3
      - android-27
      - extra-android-m2repository


  - os: osx
    language: objective-c
    xcode_destination: platform=iOS Simulator,OS=9.3,name=iPhone 5s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
  - export LANG=en_US.UTF-8
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yes | sdkmanager "platforms;android-27" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then brew install yarn ios-sim jq ios-deploy ; fi
  - nvm install 10
  - yarn global add ionic cordova

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/addkeys.sh ; fi

script:
  - yarn install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/build-ios.sh && ./travis/package-ios.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build-android.sh && ./travis/package-android.sh ; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  local-dir: ./output
